version: "3.8"

services:
  sketchmind:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    env_file:
      - ./.env
    ports:
      - "5090:5090"   # Next.js (next start)
      - "5095:5095"   # Backend (PORT)
