version: '3.8'

services:
  sketchmind:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - /app/backend/node_modules
      - /app/frontend/node_modules
    platform: linux/amd64